#cutable files for this directory
OBJECTS = 
OTHOBJS = 

# 
all:$(OBJECTS) $(OTHOBJS)

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and  files
include ../GNU_makefile_template
