#cutable files for this directory
OBJECTS = ex1_10 ex1_11 ex1_16 ex1_1 ex1_20 \
		  ex1_21 ex1_22 ex1_23 ex1_9

all:$(OBJECTS)

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and  files
include ../GNU_makefile_template

