#cutable files for this directory
OBJECTS = ex3_10 ex3_14 ex3_15 ex3_16 ex3_16_1 ex3_16_generics_version \
		  ex3_17 ex3_18 ex3_19 ex3_1a ex3_1b ex3_20a ex3_20b ex3_21 ex3_21_generics_version \
		  ex3_22 ex3_23 ex3_24 ex3_25 ex3_2a ex3_2b ex3_31 ex3_32 ex3_35 ex3_36 ex3_39 \
		  ex3_40 ex3_41 ex3_42 ex3_43 ex3_44 ex3_45 ex3_4a ex3_4b ex3_5a \
		  ex3_5b ex3_6 ex3_8

all:$(OBJECTS) 

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and  files
include ../GNU_makefile_template

