# executable files for this directory
OBJECTS = add_using.exe arrayScores.exe cctype.exe \
		  char_repl.exe cstring_hdr.exe getline.exe \
		  hexify.exe multidim.exe \
		  ptr_traversal2.exe square.exe strcompare.exe \
		  string_add.exe string_io.exe string_io2.exe \
		  string_size.exe string_size2.exe string_size3.exe \
		  vec_decls.exe vecStrings2.exe vecScores.exe \
		  vecSubs.exe word_echo.exe

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include ../GNU_makefile_template

LOCFLAGS = -I../1
