# executable files for this directory
OBJECTS = capacity.exe erase1.exe erase2.exe find_ops.exe \
		  find-str.exe refreshIter.exe stack.exe \
		  str_assignOps.exe substr.exe useConvs.exe

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include ../GNU_makefile_template

LOCFLAGS = -I..\7

