# executable files for this directory
OBJECTS = absInt.exe accum.exe accum4.exe \
		  avg_price.exe bind2.exe elimDups.exe equal.exe \
		  equiv-istream-iter.exe inserters.exe \
		  iostream_iter.exe lambda.exe newcount-size.exe \
		  ostreamIter2.exe rcomma.exe \
		  reverse.exe reverse-iter.exe rev-iters.exe \
		  sortSI.exe use_find.exe use-istream-iter.exe

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include ../GNU_makefile_template

LOCFLAGS = -I../1 -I../6

