#cutable files for this directory
OBJECTS = ex10_01_02 ex10_03_04 ex10_05 ex10_06 ex10_07 ex10_09 \
          ex10_11 ex10_12 ex10_13 ex10_16 ex10_17 ex10_18_19 \
          ex10_20_21 ex10_22 ex10_24 ex10_25 ex10_27 ex10_28 \
          ex10_29 ex10_30 ex10_31 ex10_32 ex10_33 ex10_34_35_36_37 \
	  ex10_42
all:$(OBJECTS)

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and  files
include ../GNU_makefile_template
