#cutable files for this directory
OBJECTS = ex5_10 ex5_11	ex5_12 ex5_14 ex5_14_1 ex5_17 ex5_19 ex5_20 ex5_21 \
		  ex5_23 ex5_24 ex5_25 ex5_5 ex5_6 	ex5_9

all:$(OBJECTS)

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and  files
include ../GNU_makefile_template
