# executable files for this directory
OBJECTS = add_item2.exe doWhile.exe guess.exe ifgrades.exe \
		  othercnt.exe rangefor.exe vowels.exe 

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include ../GNU_makefile_template

LOCFLAGS = -I../1

