#cutable files for this directory
OBJECTS = ex2_34 ex2_35 ex2_42_1 ex2_42_2 ex2_42_3 ex2_4

all:$(OBJECTS)

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and  files
include ../GNU_makefile_template

