#cutable files for this directory
OBJECTS = ex11_11 ex11_12_13 ex11_14 ex11_18 ex11_20 \
	  ex11_23 ex11_24_25_26 ex11_27_28_29_30 \
	  ex11_31 ex11_32 ex11_33 ex11_3_4 \
	  ex11_38 ex11_7 ex11_8 
#	  ex11_9_10  
all:$(OBJECTS)
# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and  files
include ../GNU_makefile_template
