#cutable files for this directory
OBJECTS = ex4_21 ex4_22 ex4_28

all:$(OBJECTS)

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and  files
include ../GNU_makefile_template

