#cutable files for this directory
OBJECTS = ex18.12.13.14 ex18.1.2.3 ex18.15.16.17

all:$(OBJECTS)
# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and  files
include ../GNU_makefile_template

