#cutable files for this directory
OBJECTS = ex18.12.13.14/main ex18.1.2.3/main ex18.15.16.17/main

all:$(OBJECTS)
# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and  files
include ../GNU_makefile_template

