#cutable files for this directory
OBJECTS = ex9_13 ex9_14 ex9_15 ex9_16 ex9_18 ex9_19 ex9_20 ex9_22 ex9_24 \
	ex9_26 ex9_27 ex9_31_1 ex9_31_2 ex9_32 ex9_33 ex9_34 ex9_38 \
	ex9_41 ex9_43_2 ex9_44 ex9_45 ex9_46 ex9_47_1 ex9_47_2 ex9_49 \
	ex9_50 	ex9_51 ex9_52
	# ex9_43_1.cpp can be compiled by clang or vs2012+
all:$(OBJECTS)

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and  files
include ../GNU_makefile_template
