# executable files for this directory
OBJECTS = arith-ex.exe arraysizeof.exe cond.exe \
		  incr.exe int-div.exe oofe.exe overflow.exe \
		  prec.exe shift-prec.exe sizeof_pgm.exe \
		  unaryOps.exe vec_init.exe warn_dbltoint.exe

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include ../GNU_makefile_template

LOCFLAGS = -I../2
